#! /usr/bin/python

import sys
import os
import os.path
from subprocess import call

if sys.platform == 'win32':
    print 'This installation only supports filesystems with symlink capability for now, sorry!'
    exit(1)

old_cwd = os.getcwd()
try:
    if not os.path.exists(os.path.expanduser('~/.ipython/')):
        print 'Creating default ipython profiles'
        call(['ipython', 'profile', 'create'])
    ignore_list = set(['./install', './README.md'])
    os.chdir(os.path.abspath(os.path.dirname(__file__)))

    # Find files to be symlinked
    link_paths = []
    for root, dirs, files in os.walk('.'):
        if '.git' in dirs:
            dirs.remove('.git')
    
        for f in files:
            if os.path.join(root, f) in ignore_list:
                continue
            destination = os.path.expanduser(os.path.join('~/', root, f)).replace('/./', '/')
            source = os.path.abspath(os.path.join(root, f))
            link_paths.append((source, destination))

    # Warn user if applicable
    will_be_deleted = []
    for source, destination in link_paths:
        if os.path.exists(destination):
            try:
                if os.readlink(destination) != source:
                    will_be_deleted.append(destination)
            except OSError: # not a symlink
                will_be_deleted.append(destination)
                
    if will_be_deleted:
        print 'The following files will be deleted:'
        for x in will_be_deleted:
            print '\t', x
        print 'Do you wish to continue? (y/n)',
        if raw_input().lower() != 'y':
            exit(1)
            
    # Symlink files
    for source, destination in link_paths:
        try:
            os.remove(destination)
        except OSError:
            pass
        try:
            os.makedirs(os.path.dirname(destination))
        except OSError:
            pass # leaf already exists, good!
        os.symlink(source, destination)
    
finally:
    os.chdir(old_cwd)